name: Publish Pre-Release
run-name: Publishing the release candidate package to NPM

on:
    release:
        types: [prereleased]

jobs:
    # Packages and publishes the package to NPM
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            # Setting up Node
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  registry-url: https://registry.npmjs.org/

            # Installing dependencies
            - run: yarn

            # Building the package
            - run: yarn run build

            # Publishing to NPM
            - run: npm publish --tag next
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
